/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.100
 * Generated at: 2025-03-06 09:54:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Backend.SanPham;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import DAO.CoffeDAO;
import model.SanPham;

public final class listSanPham_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Backend/Layout/footer.jsp", Long.valueOf(1740969551870L));
    _jspx_dependants.put("/Backend/Layout/header.jsp", Long.valueOf(1740969551871L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("DAO.CoffeDAO");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.SanPham");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Danh Sách Sản Phẩm</title>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/styles.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    .header {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: space-between;\r\n");
      out.write("        background: #f8f9fa; /* Màu trắng đậm hơn */\r\n");
      out.write("        padding: 10px 15px; /* Giảm chiều rộng thanh */\r\n");
      out.write("        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    }\r\n");
      out.write("    .header .logo {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        font-size: 20px; /* Nhỏ hơn một chút */\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        color: #333;\r\n");
      out.write("    }\r\n");
      out.write("    .header .logo img {\r\n");
      out.write("        height: 35px; /* Giảm kích thước logo */\r\n");
      out.write("        margin-right: 8px;\r\n");
      out.write("        border-radius: 50%; /* Bo tròn logo */\r\n");
      out.write("        object-fit: cover; /* Đảm bảo hình ảnh không bị méo */\r\n");
      out.write("    }\r\n");
      out.write("    .header nav {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        gap: 12px; /* Giảm khoảng cách giữa các menu */\r\n");
      out.write("    }\r\n");
      out.write("    .header nav a {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: #333;\r\n");
      out.write("        font-size: 15px; /* Nhỏ hơn một chút */\r\n");
      out.write("        font-weight: 500;\r\n");
      out.write("        padding: 6px 10px; /* Giảm padding của menu */\r\n");
      out.write("        transition: all 0.3s;\r\n");
      out.write("    }\r\n");
      out.write("    .header nav a:hover {\r\n");
      out.write("        color: #007bff;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("    <div class=\"logo\">\r\n");
      out.write("        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/logo.jpg\" alt=\"Logo\">\r\n");
      out.write("        Adminator\r\n");
      out.write("    </div>\r\n");
      out.write("    <nav>\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Backend/trangchu.jsp\">Trang Chủ</a>\r\n");
      out.write("    	<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Backend/NhanVien/listNhanVien.jsp\">Nhân Viên</a>\r\n");
      out.write("    	<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Backend/SanPham/listSanPham.jsp\">Sản Phẩm</a>\r\n");
      out.write("        <a href=\"#\" onclick=\"alert('Chức năng đang bảo trì!'); return false;\">Hóa Đơn</a>\r\n");
      out.write("		<a href=\"#\" onclick=\"alert('Chức năng đang bảo trì!'); return false;\">Đăng Nhập</a>\r\n");
      out.write("\r\n");
      out.write("    </nav>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("    <section>\r\n");
      out.write("        <h2 style=\"text-align: center;\">Danh Sách Sản Phẩm</h2>\r\n");
      out.write("        <div class=\"cards-container\">\r\n");
      out.write("            ");
 
            CoffeDAO dao = new CoffeDAO();
            List<SanPham> sanPhamList = dao.getAllSanPham();
            
            if (sanPhamList != null && !sanPhamList.isEmpty()) {
                for (SanPham sp : sanPhamList) {
            
      out.write("\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/");
      out.print( sp.getAnh() );
      out.write("\" alt=\"");
      out.print( sp.getTenSP() );
      out.write("\">\r\n");
      out.write("    <h3>");
      out.print( sp.getTenSP() );
      out.write("</h3>\r\n");
      out.write("    <p>Mã: ");
      out.print( sp.getMaSP() );
      out.write("</p>\r\n");
      out.write("    <p>Giá: ");
      out.print( sp.getDonGia() );
      out.write(" VND</p>\r\n");
      out.write("    <p>Đơn Vị Tính: ");
      out.print( sp.getDvt() );
      out.write("</p>\r\n");
      out.write("    <div class=\"action-buttons\">\r\n");
      out.write("        <a href=\"updateSanPham?maSP=");
      out.print( sp.getSanPhamId() );
      out.write("\" class=\"edit-btn\">Sửa</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <a href=\"deleteSanPham?maSP=");
      out.print( sp.getMaSP() );
      out.write("\" class=\"delete-btn\" onclick=\"return confirm('Bạn có chắc chắn muốn xóa?')\">Xóa</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("            ");
 
                }
            } else { 
            
      out.write("\r\n");
      out.write("                <p>Không có sản phẩm nào để hiển thị.</p>\r\n");
      out.write("            ");
 
            } 
            
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <br>\r\n");
      out.write("        <div style=\"text-align: center;\">\r\n");
      out.write("            <a href=\"addSanPham.jsp\" class=\"add-button\">Thêm Sản Phẩm</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div style=\"text-align: center; margin-top: 20px;\">\r\n");
      out.write("<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Backend/trangchu.jsp\" class=\"back-button\">Quay lại trang chủ</a></div>\r\n");
      out.write("        \r\n");
      out.write("    </section>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    .footer {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        padding: 8px 0; /* Giảm chiều cao */\r\n");
      out.write("        background: #f8f9fa; /* Màu nền đồng bộ với header */\r\n");
      out.write("        font-size: 14px; /* Font nhỏ hơn để gọn */\r\n");
      out.write("        font-weight: 500;\r\n");
      out.write("        color: #555; /* Màu chữ nhẹ hơn */\r\n");
      out.write("        box-shadow: 0 -2px 5px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("    <p>&copy; 2025 Cà Phê Luck - Nguyễn Ngọc Vỹ</p>\r\n");
      out.write("    <p>Website Quản lý cà phê Luck - Liên hệ: 0358072868</p>\r\n");
      out.write("</div>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
