/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.100
 * Generated at: 2025-03-06 12:40:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Frontend;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class userLayout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Frontend/Layout2/footer2.jsp", Long.valueOf(1741262609674L));
    _jspx_dependants.put("/Frontend/Layout2/header2.jsp", Long.valueOf(1741264805387L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Cửa Hàng Văn Phòng Phẩm Online</title>\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"font-family: Arial, sans-serif; margin: 0; padding: 0; background-color: #f8f9fa; text-align: center;\">\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    .header {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: space-between;\r\n");
      out.write("        background: #f8f9fa; /* Màu trắng đậm hơn */\r\n");
      out.write("        padding: 10px 15px; /* Giảm chiều rộng thanh */\r\n");
      out.write("        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    }\r\n");
      out.write("    .header .logo {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        font-size: 20px; /* Nhỏ hơn một chút */\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        color: #333;\r\n");
      out.write("    }\r\n");
      out.write("    .header .logo img {\r\n");
      out.write("        height: 35px; /* Giảm kích thước logo */\r\n");
      out.write("        margin-right: 8px;\r\n");
      out.write("        border-radius: 50%; /* Bo tròn logo */\r\n");
      out.write("        object-fit: cover; /* Đảm bảo hình ảnh không bị méo */\r\n");
      out.write("    }\r\n");
      out.write("    .header nav {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        gap: 12px; /* Giảm khoảng cách giữa các menu */\r\n");
      out.write("    }\r\n");
      out.write("    .header nav a {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: #333;\r\n");
      out.write("        font-size: 15px; /* Nhỏ hơn một chút */\r\n");
      out.write("        font-weight: 500;\r\n");
      out.write("        padding: 6px 10px; /* Giảm padding của menu */\r\n");
      out.write("        transition: all 0.3s;\r\n");
      out.write("    }\r\n");
      out.write("    .header nav a:hover {\r\n");
      out.write("        color: #007bff;\r\n");
      out.write("    }\r\n");
      out.write("    .search-bar input {\r\n");
      out.write("        padding: 8px;\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        width: 300px;\r\n");
      out.write("        outline: none;\r\n");
      out.write("        background-color: #dcdcdc;\r\n");
      out.write("        color: black;\r\n");
      out.write("    }\r\n");
      out.write("    .search-bar button {\r\n");
      out.write("        margin-left: 5px;\r\n");
      out.write("        padding: 8px 15px;\r\n");
      out.write("        background-color: red;\r\n");
      out.write("        color: #007bff;\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("    <div class=\"logo\">\r\n");
      out.write("        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/logopage1.png\" alt=\"Logo\">\r\n");
      out.write("        ShopMate 🛒\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Form tìm kiếm -->\r\n");
      out.write("    <nav>\r\n");
      out.write("        <form action=\"#\" method=\"GET\" class=\"search-bar\" style=\"flex-grow: 1; display: flex; justify-content: center;\">\r\n");
      out.write("            <input type=\"text\" name=\"search\" placeholder=\"Tìm kiếm sản phẩm...\" />\r\n");
      out.write("            <button type=\"submit\">🔍</button>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Frontend/userLayout.jsp\">Trang Chủ</a>\r\n");
      out.write("        <a href=\"#\" onclick=\"alert('Chức năng đang bảo trì!'); return false;\">Giỏ Hàng</a>\r\n");
      out.write("        <a href=\"#\" onclick=\"alert('Chức năng đang bảo trì!'); return false;\">Thanh Toán</a>\r\n");
      out.write("\r\n");
      out.write("        ");

            String username = (String) session.getAttribute("username");
            if (username != null) { // Nếu đã đăng nhập
        
      out.write("\r\n");
      out.write("            <span>Chào, ");
      out.print( username );
      out.write("!</span> <!-- Hiển thị tên người dùng -->\r\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() + "/Backend/User/logout" );
      out.write("\" style=\"padding: 10px; background-color: #ff4d4d; color: white; border-radius: 4px;\">Đăng Xuất</a>\r\n");
      out.write("        ");

            } else { // Nếu chưa đăng nhập
        
      out.write("\r\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() + "/Backend/User/userLogin.jsp" );
      out.write("\" style=\"padding: 10px; background-color: #4CAF50; color: white; border-radius: 4px;\">Đăng Nhập</a>\r\n");
      out.write("        ");

            }
        
      out.write("\r\n");
      out.write("    </nav>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Header -->\r\n");
      out.write("    <header style=\"background: linear-gradient(to bottom, #007bff, #ffffff); color: black; padding: 5px 0; text-align: center;\">\r\n");
      out.write("        <h1>🖊 Cửa Hàng Văn Phòng Phẩm Nhà Bách</h1>\r\n");
      out.write("        <p>Chất lượng - Tiện lợi - Giá tốt</p>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <!-- Hình ảnh giới thiệu -->\r\n");
      out.write("  <!-- Slideshow Container -->\r\n");
      out.write("    <section style=\"position: relative; width: 80%; height: 700px; margin: auto; overflow: hidden; border-radius: 10px; box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.2);\">\r\n");
      out.write("        <div style=\"display: flex; width: 500%; height: 100%; animation: slide 26s infinite;\">\r\n");
      out.write("            <div style=\"width: 100%; flex: 1;\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/biapage1.jpg\" alt=\"Hình 1\" style=\"width: 100%; height: 100%; object-fit: cover;\"></div>\r\n");
      out.write("            <div style=\"width: 100%; flex: 1;\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/biapage2.jpg\" alt=\"Hình 2\" style=\"width: 100%; height: 100%; object-fit: cover;\"></div>\r\n");
      out.write("            <div style=\"width: 100%; flex: 1;\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/biapage3.png\" alt=\"Hình 3\" style=\"width: 100%; height: 100%; object-fit: cover;\"></div>\r\n");
      out.write("            <div style=\"width: 100%; flex: 1;\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/biapage4.jpg\" alt=\"Hình 4\" style=\"width: 100%; height: 100%; object-fit: cover;\"></div>\r\n");
      out.write("            <div style=\"width: 100%; flex: 1;\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/biapage5.jpg\" alt=\"Hình 5\" style=\"width: 100%; height: 100%; object-fit: cover;\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Animation Slideshow -->\r\n");
      out.write("    <style>\r\n");
      out.write("        @keyframes slide {\r\n");
      out.write("            0% { transform: translateX(0%); }\r\n");
      out.write("            18.18% { transform: translateX(0%); } /* 3.5s dừng */\r\n");
      out.write("\r\n");
      out.write("            22% { transform: translateX(-20%); }\r\n");
      out.write("            40.18% { transform: translateX(-20%); } /* 3.5s dừng */\r\n");
      out.write("\r\n");
      out.write("            44% { transform: translateX(-40%); }\r\n");
      out.write("            62.18% { transform: translateX(-40%); } /* 3.5s dừng */\r\n");
      out.write("\r\n");
      out.write("            66% { transform: translateX(-60%); }\r\n");
      out.write("            84.18% { transform: translateX(-60%); } /* 3.5s dừng */\r\n");
      out.write("\r\n");
      out.write("            88% { transform: translateX(-80%); }\r\n");
      out.write("            100% { transform: translateX(-80%); } /* 3.5s dừng, quay lại ảnh đầu */\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("    <!-- Mô tả về cửa hàng -->\r\n");
      out.write("    <section style=\"width: 80%; margin: auto; display: flex; justify-content: space-between; align-items: center; background: white; padding: 20px; border-radius: 5px; box-shadow: 0 0 10px rgba(0,0,0,0.1);\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- Phần trái: Nội dung giới thiệu -->\r\n");
      out.write("    <div style=\"width: 55%; text-align: justify; padding-right: 20px;\">\r\n");
      out.write("        <h2 style=\"text-align: center; color: #007bff;\">Giới Thiệu Cửa Hàng</h2>\r\n");
      out.write("        <p>\r\n");
      out.write("            Chào mừng bạn đến với <strong>Văn Phòng Phẩm Online</strong> - địa chỉ đáng tin cậy chuyên cung cấp đa dạng các sản phẩm văn phòng phẩm với chất lượng cao, đáp ứng mọi nhu cầu từ học tập đến công việc văn phòng.\r\n");
      out.write("        </p>\r\n");
      out.write("        <p>\r\n");
      out.write("            Chúng tôi cam kết mang đến những sản phẩm tốt nhất với **giá cả hợp lý**, hỗ trợ tối đa cho cá nhân, doanh nghiệp và trường học trong việc sử dụng các dụng cụ văn phòng thiết yếu.\r\n");
      out.write("            Với phương châm <strong>\"Chất lượng - Tiện lợi - Giá tốt\"</strong>, cửa hàng chúng tôi không ngừng đổi mới, cập nhật các sản phẩm mới nhất để đáp ứng xu hướng tiêu dùng hiện đại.\r\n");
      out.write("        </p>\r\n");
      out.write("        <p>\r\n");
      out.write("            Với hơn **5 năm kinh nghiệm**, chúng tôi tự hào là nhà cung cấp **sỉ và lẻ** các sản phẩm văn phòng phẩm chất lượng cao, phục vụ hàng nghìn khách hàng trên toàn quốc.\r\n");
      out.write("        </p>\r\n");
      out.write("        <p><strong>Chúng tôi cung cấp:</strong></p>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li>✏ <strong>Bút các loại:</strong> Bút bi, bút chì, bút dạ quang, bút lông bảng, bút máy.</li>\r\n");
      out.write("            <li>📖 <strong>Giấy - Vở:</strong> Vở học sinh, sổ ghi chú, giấy in A4, A5, giấy màu, giấy mỹ thuật.</li>\r\n");
      out.write("            <li>📏 <strong>Dụng cụ học tập:</strong> Thước kẻ, compa, bảng vẽ, dụng cụ đo lường.</li>\r\n");
      out.write("            <li>📌 <strong>Văn phòng phẩm:</strong> Kẹp giấy, hồ dán, băng keo, ghim bấm, kéo cắt giấy.</li>\r\n");
      out.write("            <li>💼 <strong>Hồ sơ - Lưu trữ:</strong> Bìa hồ sơ, file tài liệu, túi đựng giấy tờ, kẹp ghim.</li>\r\n");
      out.write("            <li>📂 <strong>Đồ dùng văn phòng:</strong> Máy tính cầm tay, bấm kim, bảng ghi chú, sticker văn phòng.</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <p>\r\n");
      out.write("            Bên cạnh đó, chúng tôi luôn có **chính sách ưu đãi đặc biệt** cho khách hàng đặt hàng số lượng lớn, hỗ trợ giao hàng nhanh chóng, tiện lợi.\r\n");
      out.write("            Nếu bạn đang tìm kiếm một địa chỉ mua sắm văn phòng phẩm uy tín, hãy để **Văn Phòng Phẩm Online** đồng hành cùng bạn!\r\n");
      out.write("        </p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Phần phải: Hình ảnh minh họa -->\r\n");
      out.write("    <div style=\"width: 40%; text-align: center;\">\r\n");
      out.write("        <a>Có thể bạn sẽ thích</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
